const data = {
    products: [
        {
            id: 1,
            name: "Free Shirt",
            slug: "free-shirt",
            category: "Shirts",
            price: 70,
            image: "/images/shirt1.jpg",
            brand: "Nike",
            numReviews: 10,
            rating: 4.5,
            countInStock: 20,
            description: "A popular Shirt",
        },
        {
            id: 2,
            name: "Fit Shirt",
            slug: "fit-shirt",
            category: "Shirts",
            price: 80,
            image: "/images/shirt2.jpg",
            brand: "Adidas",
            numReviews: 12,
            rating: 4.3,
            countInStock: 17,
            description: "A popular Shirt",
        },
        {
            id: 3,
            name: "Slim Shirt",
            slug: "slim-shirt",
            category: "Shirts",
            price: 70,
            image: "/images/shirt3.jpg",
            brand: "Raymond",
            numReviews: 15,
            rating: 4.6,
            countInStock: 20,
            description: "A popular Shirt",
        },
        {
            id: 4,
            name: "Golf Pants",
            slug: "golf-pants",
            category: "Pants",
            price: 120,
            image: "/images/pants1.jpg",
            brand: "Olivia",
            numReviews: 8,
            rating: 4.6,
            countInStock: 25,
            description: "A popular Pants",
        },
        {
            id: 5,
            name: "Slim Pants",
            slug: "slim-pants",
            category: "Pants",
            price: 40,
            image: "/images/pants2.jpg",
            brand: "Nike",
            numReviews: 20,
            rating: 4.7,
            countInStock: 25,
            description: "A popular trousers",
        },
    ],
};

export default data;
